# Generated by Django 6.0.3 on 2026-04-01 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyengSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(choices=[('career_guidance', 'Профориентация'), ('python', 'Python'), ('soft_skills', 'Soft Skills'), ('english', 'Английский'), ('math', 'Математика'), ('managment_of_project', 'Менеджмент проектов'), ('lessons_about_main', 'Курс Сингулярности'), ('onboarding', 'Онбординг'), ('biology', 'Биология'), ('history', 'История'), ('social_studies', 'Обществознание'), ('physics', 'Физика'), ('geography', 'География'), ('literature', 'Литература'), ('basics_of_security', 'Основы безопасности'), ('chemistry', 'Химия'), ('russian', 'Русский язык')], max_length=50, verbose_name='Ключ предмета')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('api_version', models.CharField(choices=[('v1', 'API v1'), ('v2', 'API v2'), ('v3', 'API v3')], max_length=10, verbose_name='Версия API')),
                ('has_active_program', models.BooleanField(default=False, verbose_name='Есть активная программа')),
                ('last_parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Последний парсинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skyeng_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['subject_name'],
                'unique_together': {('user', 'subject_key')},
            },
        ),
        migrations.CreateModel(
            name='SkyengMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_current', models.IntegerField(default=0, verbose_name='Пройдено уроков')),
                ('lessons_total', models.IntegerField(default=0, verbose_name='Всего уроков')),
                ('lessons_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Рейтинг уроков')),
                ('homework_current', models.IntegerField(default=0, verbose_name='Сдано ДЗ')),
                ('homework_total', models.IntegerField(default=0, verbose_name='Всего ДЗ')),
                ('homework_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Средний балл ДЗ')),
                ('tests_current', models.IntegerField(default=0, verbose_name='Пройдено тестов')),
                ('tests_total', models.IntegerField(default=0, verbose_name='Всего тестов')),
                ('tests_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Средний балл тестов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='parse_avatar.skyengsubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='SkyengStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.IntegerField(verbose_name='ID потока')),
                ('title', models.CharField(max_length=200, verbose_name='Название потока')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='parse_avatar.skyengsubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'unique_together': {('subject', 'stream_id')},
            },
        ),
        migrations.CreateModel(
            name='SkyengProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(verbose_name='ID программы')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='parse_avatar.skyengsubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'unique_together': {('subject', 'program_id')},
            },
        ),
        migrations.CreateModel(
            name='SkyengLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(verbose_name='ID урока')),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='ID задания')),
                ('title', models.CharField(max_length=300, verbose_name='Название урока')),
                ('lesson_type', models.CharField(choices=[('self_study', 'Самостоятельная работа'), ('test', 'Тест'), ('homework', 'Домашняя работа'), ('lesson', 'Урок')], max_length=20, verbose_name='Тип урока')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('passed', 'Пройден'), ('locked', 'Заблокирован'), ('expired', 'Истёк')], max_length=20, verbose_name='Статус')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Оценка')),
                ('available_at', models.DateTimeField(blank=True, null=True, verbose_name='Доступен с')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('homework_url', models.URLField(blank=True, verbose_name='Ссылка на ДЗ')),
                ('lesson_url', models.URLField(blank=True, verbose_name='Ссылка на урок')),
                ('teacher_name', models.CharField(blank=True, max_length=200, verbose_name='Преподаватель')),
                ('module_title', models.CharField(blank=True, max_length=200, verbose_name='Модуль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='parse_avatar.skyengsubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['available_at'],
                'unique_together': {('subject', 'lesson_id')},
            },
        ),
    ]
