# Generated by Django 6.0.3 on 2026-04-01 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_token', models.TextField(blank=True, null=True, verbose_name='Google Access Token')),
                ('google_refresh_token', models.TextField(blank=True, null=True, verbose_name='Google Refresh Token')),
                ('google_token_uri', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Token URI')),
                ('google_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Client ID')),
                ('google_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Client Secret')),
                ('google_scopes', models.TextField(blank=True, help_text='JSON array scopes', null=True, verbose_name='Google Scopes (JSON)')),
                ('google_token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Google Token Expiry')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Google Email')),
                ('skyeng_token', models.TextField(blank=True, null=True, verbose_name='Skyeng Access Token')),
                ('skyeng_refresh_token', models.TextField(blank=True, null=True, verbose_name='Skyeng Refresh Token')),
                ('skyeng_token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Skyeng Token Expiry')),
                ('skyeng_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Skyeng Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_sync_google', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync Google')),
                ('last_sync_skyeng', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync Skyeng')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credentials',
                'verbose_name_plural': 'User Credentials',
                'db_table': 'user_credentials',
            },
        ),
    ]
